import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:starmap/sky/angles.dart';
import 'package:starmap/sky/observer.dart';
import 'package:starmap/sky/planets.dart';
import 'package:starmap/sky/sun.dart';

/// How wrong is this app about the sky?
///
/// Not "is it right" - everything is wrong at some decimal place, and a test that only asserts a
/// threshold hides how much headroom is left. This measures the error against NASA/JPL's own
/// ephemeris for every body, at four epochs, from four places on Earth, and PRINTS it. The
/// numbers in the README come from this output and nowhere else.
///
/// Fixtures: test/fixtures/horizons.json, generated by data/make_fixtures.py. Committed, so this
/// test needs no network and so a change in the reference shows up as a reviewable diff.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/horizons.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  final sites = (fixture['sites'] as Map<String, dynamic>).map(
    (name, value) => MapEntry(
      name,
      Observer(
        latitudeDegrees: (value['lat_deg'] as num).toDouble(),
        longitudeEastDegrees: (value['lon_east_deg'] as num).toDouble(),
        altitudeMetres: (value['alt_km'] as num).toDouble() * 1000.0,
      ),
    ),
  );

  final observations = (fixture['observations'] as List<dynamic>)
      .cast<Map<String, dynamic>>();

  const planetsByName = {
    'mercury': Planet.mercury,
    'venus': Planet.venus,
    'mars': Planet.mars,
    'jupiter': Planet.jupiter,
    'saturn': Planet.saturn,
    'uranus': Planet.uranus,
    'neptune': Planet.neptune,
  };

  group('position accuracy against JPL Horizons', () {
    final separationsArcsec = <String, List<double>>{};
    final elevationErrorsArcsec = <String, List<double>>{};

    test('every body at every site and epoch', () {
      for (final row in observations) {
        final body = row['body'] as String;
        if (body == 'moon') continue; // the Moon has its own test file
        final observer = sites[row['site']]!;
        final when = DateTime.parse(row['utc'] as String).toUtc();

        final TopocentricPosition computed;
        if (body == 'sun') {
          computed = toTopocentric(
            geocentric: sunPosition(when),
            distanceAu: sunDistanceAu(when),
            observer: observer,
            when: when,
          );
        } else {
          final planet = planetsByName[body]!;
          computed = toTopocentric(
            geocentric: geocentricPosition(planet, when),
            distanceAu: distanceFromEarthAu(planet, when),
            observer: observer,
            when: when,
          );
        }

        final separation = angularSeparationDegrees(
          computed.position.rightAscensionDegrees,
          computed.position.declinationDegrees,
          (row['ra_deg'] as num).toDouble(),
          (row['dec_deg'] as num).toDouble(),
        );
        final elevationError = (computed.horizontal.altitudeDegrees -
                (row['elevation_deg'] as num).toDouble())
            .abs();

        separationsArcsec.putIfAbsent(body, () => []).add(separation * 3600);
        elevationErrorsArcsec
            .putIfAbsent(body, () => [])
            .add(elevationError * 3600);
      }

      // Printed, then asserted. The print is the deliverable; the assertion stops a regression.
      final names = separationsArcsec.keys.toList()..sort();
      // ignore: avoid_print
      print('\n  body      n   median sep   worst sep   worst elevation error');
      // ignore: avoid_print
      print('  ${'-' * 62}');
      for (final name in names) {
        final separations = separationsArcsec[name]!..sort();
        final elevations = elevationErrorsArcsec[name]!..sort();
        final median = separations[separations.length ~/ 2];
        // ignore: avoid_print
        print(
          '  ${name.padRight(9)} ${separations.length.toString().padLeft(2)}   '
          '${_arcsec(median).padLeft(10)}  ${_arcsec(separations.last).padLeft(10)}  '
          '${_arcsec(elevations.last).padLeft(18)}',
        );
      }

      for (final name in names) {
        final worst = separationsArcsec[name]!.reduce((a, b) => a > b ? a : b);
        expect(
          worst,
          lessThan(3600),
          reason:
              '$name is off by ${_arcsec(worst)}, which is more than a degree. That is not '
              'orbital-element error, that is a bug.',
        );
      }
    });
  });

  test('a date outside JPL\'s fitted interval is refused, not extrapolated', () {
    expect(
      () => geocentricPosition(Planet.jupiter, DateTime.utc(2100, 1, 1)),
      throwsA(isA<OutsideValidRangeException>()),
    );
    expect(
      () => geocentricPosition(Planet.jupiter, DateTime.utc(1700, 1, 1)),
      throwsA(isA<OutsideValidRangeException>()),
    );
  });
}

String _arcsec(double value) {
  if (value < 60) return '${value.toStringAsFixed(1)}"';
  if (value < 3600) return '${(value / 60).toStringAsFixed(2)}\'';
  return '${(value / 3600).toStringAsFixed(3)}°';
}
